# Generated by Django 4.2.3 on 2023-07-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggesteddish',
            options={'verbose_name': 'Suggested Dish',
                     'verbose_name_plural': 'Suggested Dishes'},
        ),
    ]
