# Generated by Django 4.2.3 on 2023-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userreview_name_userreview_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreview',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='userreview',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='userreview',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='userreview',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
