# Generated by Django 4.2.3 on 2023-07-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userreview',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
