# Generated by Django 4.2.3 on 2023-08-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_userreview_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='suggested_dishes/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Suggested Dish',
                'verbose_name_plural': 'Suggested Dishes',
            },
        ),
    ]
