# Generated by Django 4.2.3 on 2023-08-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_suggesteddish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestedDish',
        ),
    ]
