# Generated by Django 4.2.3 on 2023-08-13 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_delete_suggesteddish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreview',
            options={'ordering': ['-created_on'],
                     'verbose_name_plural': 'User Reviews'},
        ),
        migrations.AlterField(
            model_name='userreview',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='author',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='comment',
            field=models.TextField(max_length=500, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='created_on',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.IntegerField(
                choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='slug',
            field=models.SlugField(
                max_length=200,
                null=True,
                unique=True,
                verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'Draft'), (1, 'Published')],
                default=0,
                verbose_name='Status',
            ),
        ),
    ]
